### ISSUE TITLE
Game performance issue 

### ISSUE THREAD

**Issue by DamienMaxwell-MGS** [Hackswell/GloryOfEfficiency#9]
The game becomes laggy when casting the fishing rod, especially when the fishing hook is about to dip into the water.

**Comment by Exaxxion** [comment]
Experiencing the same in 1.5.0alpha3.

If you check the SMAPI console, a gargantuan amount of debug log output is being generated every time you fish. Seems possibly related to the probability box changes.

Auto-Fishing also still voids all non-fish items pulled from the water like in #2, which was supposedly fixed in this version. Took me a couple trash items and a jelly to realize it.

**Comment by mttmmj** [comment]
[JoysOfEfficiency] [FishingProbabilitiesInfo]dictFish: Adding 151 :: 0.46999999731779096
[JoysOfEfficiency] This mod failed in the GameLoop.UpdateTicked event. Technical details:
ArgumentException: An item with the same key has already been added. Key: 151
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at JoysOfEfficiency.Huds.FishingProbabilitiesBox.GetFishes(Int32 waterDepth, Farmer who, String locationName) in /home/woody/working/JoysOfEfficiency/JoysOfEfficiency/Huds/FishingProbabilitiesBox.cs:line 240
   at JoysOfEfficiency.Huds.FishingProbabilitiesBox.GetFishes(GameLocation location, Int32 bait, Int32 waterDepth, Farmer who, Int32 trial) in /home/woody/working/JoysOfEfficiency/JoysOfEfficiency/Huds/FishingProbabilitiesBox.cs:line 83
   at JoysOfEfficiency.Huds.FishingProbabilitiesBox.UpdateProbabilities(FishingRod rod) in /home/woody/working/JoysOfEfficiency/JoysOfEfficiency/Huds/FishingProbabilitiesBox.cs:line 46
   at JoysOfEfficiency.EventHandler.UpdateEvents.OnEveryUpdate() in /home/woody/working/JoysOfEfficiency/JoysOfEfficiency/EventHandler/UpdateEvents.cs:line 53
   at JoysOfEfficiency.EventHandler.UpdateEvents.OnGameUpdateEvent(Object sender, UpdateTickedEventArgs args) in /home/woody/working/JoysOfEfficiency/JoysOfEfficiency/EventHandler/UpdateEvents.cs:line 29
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by Hackswell** [comment]
Sorry about that!  I'll fix the logging in ALPHA 4.  I hadn't realized I was using regular SMAPI, then I installed dev, and forgot to revert.   Thanks!

**Comment by DamienMaxwell-MGS** [comment]
> Sorry about that! I'll fix the logging in ALPHA 4. I hadn't realized I was using regular SMAPI, then I installed dev, and forgot to revert. Thanks!

Thanks!  And I found another bug. Auto water will ignore the bottomless enchantment. The bottomless watering can be empty.

**Comment by Hackswell** [comment]
Should be fixed in ALPHA 4 code now.
